### ISSUE TITLE
[docs]: chores

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/curriculum-helpers#106]
```[tasklist]
### Tasks
- [ ] add documentation for `python.getDef`
- [ ] add documentation for `python.getBlock`
- [ ] add documentation for `python.removeComments`
- [ ] add documentation for `CSSHelp`
- [ ] add `.gitpod.yml` config to help with tooling setup
- [ ] add documentation for contributing
- [ ] add documentation for other helpers
```

**Comment by ShaunSHamilton** [comment]
Closing as we are moving documentation over to `contribute`
